#ifndef RAJ_CONFIGURATION_HH
#define RAJ_CONFIGURATION_HH

// Configuration de tailles :
#define C_WINDOW_HIGHT 720
#define C_WINDOW_LENGTH 1280

#define C_NORMAL_UNIT_DIAMETRE 100

#endif // RAJ_CONFIGURATION_HH
